## Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.axes as ax

from sklearn import datasets
import warnings
warnings.filterwarnings("ignore")

## Loading Data

In [4]:
data = datasets.fetch_california_housing()

In [5]:
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

## Data 

In [7]:
x = data.data

In [8]:
x

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [9]:
y = data.target

In [10]:
features = data.feature_names
features

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [12]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(16512, 8) (16512,)
(4128, 8) (4128,)


## <font color = "Red">Random Forest</font>

In [14]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(100)
rf = rf.fit(x_train, y_train)

In [15]:
predictions = rf.predict(x_test)

In [16]:
predictions.shape

(4128,)

In [17]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, predictions)

0.26221651203872326

## <font color = "Red">K - Fold Cross Validation</font>

In [19]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits = 5, shuffle = False)

for train_index, test_index in kfold.split(x):
    print("Train - \n", train_index, "\ntest - \n", test_index)
    print("=========\n")

Train - 
 [ 4128  4129  4130 ... 20637 20638 20639] 
test - 
 [   0    1    2 ... 4125 4126 4127]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
test - 
 [4128 4129 4130 ... 8253 8254 8255]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
test - 
 [ 8256  8257  8258 ... 12381 12382 12383]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
test - 
 [12384 12385 12386 ... 16509 16510 16511]

Train - 
 [    0     1     2 ... 16509 16510 16511] 
test - 
 [16512 16513 16514 ... 20637 20638 20639]



In [37]:
rf1= RandomForestRegressor()
n_est = [100, 200, 500]
for n_estimator in n_est:       
    error = []
    for train_index, test_index in kfold.split(x):
        x_train, x_test = x[train_index], x[test_index]
        y_train, y_test = y[train_index], y[test_index]
        rf1 = RandomForestRegressor(n_estimator)
        rf1 = rf1.fit(x_train, y_train)
        prediction = rf1.predict(x_test)
        error.append(mean_squared_error(y_test, prediction))
    print("Results for n_estimator: ", n_estimator)
    print(error)
    print("Average Error = ", sum(error)/len(error))

Results for n_estimator:  100
[0.5300532553427706, 0.346032824798509, 0.3726105639755796, 0.43019236962911134, 0.46527370403307006]
Average Error =  0.4288325435558081
Results for n_estimator:  200
[0.5195611742801269, 0.34350366145051003, 0.37070686943587045, 0.44722776529058084, 0.46499347130885693]
Average Error =  0.4291985883531891
Results for n_estimator:  500
[0.5279073282519346, 0.3431546239362382, 0.3701240757309286, 0.44160381921576336, 0.46270982425868357]
Average Error =  0.4290999342787097


In [39]:
error

[0.5279073282519346,
 0.3431546239362382,
 0.3701240757309286,
 0.44160381921576336,
 0.46270982425868357]